CREATE TABLE Submissions (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    age VARCHAR(30) NOT NULL,
    sex VARCHAR(30) NOT NULL,
    future VARCHAR(30) NOT NULL,
    democracy INT(5),
    money INT(5),
    success INT(5),
    education INT(5),
    health INT(5),
    environment INT(5),
    family INT(5),
    futurelist VARCHAR(50),
    changefuture VARCHAR(30),
    climatechange VARCHAR(30),
    sustainability VARCHAR(30) NOT NULL,
    sustainabilityscale INT(5),
    nosustainability VARCHAR(30),
    sustainabilityeveryday VARCHAR(30),
    sustainabilityactions VARCHAR(500),
    nosustainabilitymotivation VARCHAR(30),
    sustainabilitymotivation VARCHAR(500),
    source VARCHAR(30) NOT NULL,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)